spring.application.name=backend
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/titikkoma
spring.datasource.username=postgres

# Hibernate membuat dan menyesuaikan tabel otomatis dari class @Entity
spring.jpa.hibernate.ddl-auto=update
# Tampilkan perintah SQL di log, berguna saat belajar
spring.jpa.show-sql=true